// <auto-generated />
using HurryAppPleaseWork.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HurryAppPleaseWork.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HurryAppPleaseWork.Models.ProbRectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProbResultId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Template")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ProbResultId");

                    b.ToTable("ResultsTemplate");
                });

            modelBuilder.Entity("HurryAppPleaseWork.Models.ProbResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageMatrix")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("HurryAppPleaseWork.Models.ProbRectTemplate", b =>
                {
                    b.HasOne("HurryAppPleaseWork.Models.ProbResult", null)
                        .WithMany("Templates")
                        .HasForeignKey("ProbResultId");

                    b.OwnsOne("HurryAppPleaseWork.Models.RectRecord", "Rect", b1 =>
                        {
                            b1.Property<int>("ProbRectTemplateId")
                                .HasColumnType("integer");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ProbRectTemplateId");

                            b1.ToTable("ResultsTemplate");

                            b1.WithOwner()
                                .HasForeignKey("ProbRectTemplateId");
                        });

                    b.Navigation("Rect")
                        .IsRequired();
                });

            modelBuilder.Entity("HurryAppPleaseWork.Models.ProbResult", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
